### PR TITLE
Change RNG version

### LINKED ISSUE #90: with_rng_version() would be nice
To ease fixing the new RNG madness in 3.6.0.

### PR DESCRIPTION
**Pull request by gaborcsardi**
Closes #90.

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks! It looks good!

Can you please add a bullet to NEWS? It should briefly [describe the change](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by gaborcsardi** [comment]
Done. Travis R 3.1 fails of course....

**Comment by gaborcsardi** [comment]
Btw. `(@yourname, #issuenumber)` or the reverse order? withr seems to use the latter?

**Comment by jimhester** [comment]
Go with what withr uses I guess, it is a saved reply :)

**Comment by jimhester** [comment]
Thanks!

Great work, this package is now better thanks to you!

Thanks!! You are da bomb!

**Pull request merged**
